### PR TITLE
Create an account with an email with no digits

### PR DESCRIPTION
**Pull request by AndreiH**
@bobsilverberg r?

### CODE REVIEW

**Comment by bobsilverberg** [comment]
@AndreiH There is a problem with receiving the registration email with this code, which is causing the tests to fail. For example,

```
_________________________________________________ TestCreateAccount.test_create_new_account _________________________________________________

self = <tests.test_create_account.TestCreateAccount object at 0x10cbab850>

    def test_create_new_account(self):
>       acct = FxATestAccount(use_prod=False).create_account()

tests/test_create_account.py:19:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <fxapom.fxapom.FxATestAccount instance at 0x10eabf758>

    def create_account(self):
        self.account = TestEmailAccount()
        changed_email = map(lambda x: random.choice(string.ascii_lowercase) if x.isdigit() else x, self.account.email)
        self.new_email = ''.join([i for i in changed_email])
        client = Client(self.fxa_url)
        print 'fxapom created an account for email: %s at %s' % (self.new_email, datetime.now())
        # Create and verify the Firefox account
        self.session = client.create_account(self.new_email, self.password)
        m = self.account.wait_for_email(lambda m: "x-verify-code" in m["headers"])
        if not m:
>           raise RuntimeError("Verification email was not received")
E           RuntimeError: Verification email was not received

fxapom/fxapom.py:49: RuntimeError
```

**Comment by AndreiH** [comment]
I think this will not work.
As you can see in <code>fxa.tests.utils</code> we have <code>wait_for_email</code> that uses <code>find_email</code> and this calls <code>self.messages</code>. We can see in <code>__init__</code> that the messages are collected from the <code>{uniq}</code> email that is created in the first place. Can you confirm this @bobsilverberg ?

**Comment by bobsilverberg** [comment]
@AndreiH We need to pass in an email address that matches the pattern that the method expects. This will work:

```
    def create_account(self):
        random_string = ''.join(random.choice(string.ascii_lowercase) for _ in range(10))
        email_pattern = random_string + '@{hostname}'
        self.account = TestEmailAccount(email=email_pattern)
        client = Client(self.fxa_url)
        print 'fxapom created an account for email: %s at %s' % (self.account.email, datetime.now())
        # Create and verify the Firefox account
        self.session = client.create_account(self.account.email, self.password)
        m = self.account.wait_for_email(lambda m: "x-verify-code" in m["headers"])
        if not m:
            raise RuntimeError("Verification email was not received")
        self.session.verify_email_code(m["headers"]["x-verify-code"])
        return self
```
I am going to update this myself and commit it to see if it solves our problem with the other PR.

**Comment by bobsilverberg** [comment]
My updated version of this landed in https://github.com/bobsilverberg/fxapom/commit/1ed4562a4d9fb712c2f4f328188cd380d5b5b072

**Pull request closed without merging**
